# 定数
const_file = "lesson17_projects/house3/data/const.json"

# 状態遷移
transition_file = "lesson10020_projects/house3n2/auto_gen/data/transition3.json"

# 状態ファイル出力ディレクトリー
output_states_dir = "lesson23_projects/house3n2/auto_gen/code/states1"

[import_module]
const = "lesson23_projects.house3n2.auto_gen.data.const"
state_gen = "lesson23_projects.house3n2.data.state_gen_v23"
