# 定数ファイル
input_const_file = "lesson17_projects/house3/data/const.json"

# 状態遷移ファイル
transition_file = "lesson13_projects/house3/data/transition.json"
output_states_dir = "lesson18_projects/house3/auto_gen/code/states1"

[import_module]
const = "lesson17_projects.house3.auto_gen.data.const"
