# 定数ファイル
input_const_file = "lesson17_projects/pen/data/const.json"

# 状態遷移ファイル
transition_file = "lesson14_projects/pen/data/transition.json"
output_states_dir = "lesson18_projects/pen/auto_gen/code/states"

[import_module]
const = "lesson17_projects.pen.auto_gen.data.const"
