# 定数
const_file = "lesson18n2_projects/wcsc/data/const.json"

# 状態遷移
transition_file = "lesson20_projects/wcsc/auto_gen/data/transition.json"

# 状態ファイル出力ディレクトリー
output_states_dir = "lesson23_projects/wcsc/auto_gen/code/states1"

[import_module]
const = "lesson23_projects.wcsc.auto_gen.data.const"
