# 定数
const_file = "lesson17_projects/wcsc/data/const.json"

# 状態遷移
transition_file = "lesson10020_projects/wcsc/auto_gen/data/transition.json"

# 状態ファイル出力ディレクトリー
output_states_dir = "lesson23_projects/wcsc/auto_gen/code/states1"

[import_module]
const = "lesson17_projects.wcsc.auto_gen.data.const"
state_gen = "lesson23_projects.wcsc.data.state_gen_v23"
